# Generated by Django 4.2.6 on 2023-10-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionoption",
            name="index",
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="content",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
