# run with --ask-become-pass

- name: Deploy application
  hosts: servers
  become: true
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Ensure git is installed.
      package: name=git

    - name: Ensure docker is installed.
      package: name=docker

    - name: Delete old .env file
      ansible.builtin.file:
        state: absent
        path: /opt/leadanne2/.env

    - name: Get stuff from git
      git:
        repo: https://github.com/Z33DD/leadanne2.git
        version: main
        clone: true
        update: true
        dest: /opt/leadanne2/

    - name: Copy .env file
      ansible.builtin.copy:
        src: ../.env
        dest: /opt/leadanne2/.env

    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: /opt/leadanne2/docker-compose.yml

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /opt/leadanne2/
      register: output
