# run with --ask-become-pass

- name: Deploy application
  hosts: servers
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Ensure docker is installed.
      package: name=docker

    - name: Copy code to remote location
      ansible.posix.synchronize:
        src: "{{playbook_dir}}/../"
        dest: /opt/leadanne2/
        partial: true
        private_key: ~/.ssh/id_rsa
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.venv"
          - "--exclude=*.pyc"

    - name: Build and start services
      community.docker.docker_compose_v2:
        project_src: /opt/leadanne2/
        build: always
      register: output
