# run with --ask-become-pass

- name: Deploy application
  hosts: servers
  become: true
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Ensure docker is installed.
      package: name=docker

    - name: Delete old content
      ansible.builtin.file:
        state: absent
        path: /opt/leadanne2/*

    - name: Copy code to remote location
      ansible.builtin.copy:
        src: "./"
        dest: /opt/leadanne2/

    - name: Set environment variable
      ansible.builtin.shell:
        cmd: "export ENV=production"

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /opt/leadanne2/
      register: output
