"""
Django settings for leadanne2 project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import tomllib
from dotenv import load_dotenv

load_dotenv()


def get_project_config() -> dict:
    with open("pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    return data["tool"]["poetry"]


PROJECT = get_project_config()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", False)

ALLOWED_HOSTS = ["*"]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SENTRY_DSN = os.getenv("SENTRY_DSN")
ENV = os.getenv("ENV")

RESEND_API_KEY = os.getenv("RESEND_API_KEY")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
AWS_REGION = os.getenv("AWS_REGION")
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")

SUPABASE_URL = os.environ.get("SUPABASE_URL", "http://localhost:54321")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

REFERENCE = {
    "nGpZDL": {
        "template_id": os.getenv("POSTMARK_TEMPLATE_ID_EN"),
        "language": "English",
        "fields": {
            "company_information": "question_RWGZbp",
            "email": "question_o9b05X",
            "problem": "question_Gexoq2",
        },
    },
    "wQ7k87": {
        "template_id": os.getenv("POSTMARK_TEMPLATE_ID_PT"),
        "language": "Portuguese",
        "fields": {
            "company_information": "question_jea0z9",
            "email": "question_2jEbob",
            "problem": "question_4a41Oo",
        },
    },
}
